### ISSUE TITLE
How to implement reverse geocoding?

### ISSUE THREAD

**Issue by is-undefined** [jshimko/meteor-geocomplete#36]
I want to get the location by using lat and lng as input

**Comment by jshimko** [comment]
This is just a wrapper for using Geocomplete with Meteor's Atmosphere package system, so it's probably not the best place to go for support on using the library.  I didn't write Geocomplete and I don't support it, so I recommend asking over at the [official Geocomplete repo](https://github.com/ubilabs/geocomplete).  

Also, if your Meteor app is running v1.3 or later, I highly recommend using the npm version of Geocomplete instead of this one.  I don't update/maintain this package anymore because npm is a better way to make sure you're always using the latest version from the official author.

```sh
npm install --save geocomplete

meteor remove jeremy:geocomplete
```
